Movie_recommendation/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/', include('polls.urls')),
    path('movies/', include('movies.urls')),
    path('captcha', include('captcha.urls')),  # 增加这一行
]

movies/urls.py
from django.urls import path,include
from . import views

app_name = 'movies'

urlpatterns = [
    path('', views.index, name='index'),
    # ex: /movies/5/
    path('<int:movie_id>/', views.detail, name='detail'),
    # ex: /movies/5/rate
    path('<int:movie_id>/rate', views.rate, name='rate'),

    path('login/', views.login, name='login'),

    path('logout/', views.logout, name='logout'),

    path('register/', views.register, name='register'),

    path('search', views.search, name='search'),

    path('user/<str:user_id>', views.user, name='user'),

    path('rec', views.rec, name='rec'),
]

polls/urls.py
from django.urls import path

from . import views

# When processing a request, Django starts at the first pattern in urlpatterns

# 添加下面字段可以让程序更加清晰
app_name = 'polls'

urlpatterns = [
    path('', views.index, name='index'),
    # ex: /polls/5/
    path('<int:question_id>/', views.detail, name='detail'),
    # ex: /polls/5/results/
    path('<int:question_id>/results/', views.results, name='results'),
    # ex: /polls/5/vote/
    path('<int:question_id>/vote/', views.vote, name='vote'),
    # path('', views.IndexView.as_view(), name='index'),
    # path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    # path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    # path('<int:question_id>/vote/', views.vote, name='vote'),

]

movies/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey and OneToOneField has `on_delete` set to the desired behavior
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models


class AuthGroup(models.Model):
    name = models.CharField(unique=True, max_length=150)

    class Meta:
        managed = False
        db_table = 'auth_group'


class AuthGroupPermissions(models.Model):
    group = models.ForeignKey(AuthGroup, models.DO_NOTHING)
    permission = models.ForeignKey('AuthPermission', models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_group_permissions'
        unique_together = (('group', 'permission'),)


class AuthPermission(models.Model):
    name = models.CharField(max_length=255)
    content_type = models.ForeignKey('DjangoContentType', models.DO_NOTHING)
    codename = models.CharField(max_length=100)

    class Meta:
        managed = False
        db_table = 'auth_permission'
        unique_together = (('content_type', 'codename'),)


class AuthUser(models.Model):
    password = models.CharField(max_length=128)
    last_login = models.DateTimeField(blank=True, null=True)
    is_superuser = models.IntegerField()
    username = models.CharField(unique=True, max_length=150)
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=150)
    email = models.CharField(max_length=254)
    is_staff = models.IntegerField()
    is_active = models.IntegerField()
    date_joined = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'auth_user'


class AuthUserGroups(models.Model):
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)
    group = models.ForeignKey(AuthGroup, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_user_groups'
        unique_together = (('user', 'group'),)


class AuthUserUserPermissions(models.Model):
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)
    permission = models.ForeignKey(AuthPermission, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_user_user_permissions'
        unique_together = (('user', 'permission'),)


class DjangoAdminLog(models.Model):
    action_time = models.DateTimeField()
    object_id = models.TextField(blank=True, null=True)
    object_repr = models.CharField(max_length=200)
    action_flag = models.PositiveSmallIntegerField()
    change_message = models.TextField()
    content_type = models.ForeignKey('DjangoContentType', models.DO_NOTHING, blank=True, null=True)
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'django_admin_log'


class DjangoContentType(models.Model):
    app_label = models.CharField(max_length=100)
    model = models.CharField(max_length=100)

    class Meta:
        managed = False
        db_table = 'django_content_type'
        unique_together = (('app_label', 'model'),)


class DjangoMigrations(models.Model):
    app = models.CharField(max_length=255)
    name = models.CharField(max_length=255)
    applied = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'django_migrations'


class DjangoSession(models.Model):
    session_key = models.CharField(primary_key=True, max_length=40)
    session_data = models.TextField()
    expire_date = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'django_session'


class Info(models.Model):
    id = models.IntegerField(primary_key=True)
    title = models.CharField(max_length=255, blank=True, null=True)
    pubdates = models.CharField(max_length=255, blank=True, null=True)
    durations = models.CharField(max_length=255, blank=True, null=True)
    genres = models.CharField(max_length=4095, blank=True, null=True)
    countries = models.CharField(max_length=255, blank=True, null=True)
    image = models.CharField(max_length=4095, blank=True, null=True)
    summary = models.TextField(blank=True, null=True)
    star_five = models.IntegerField()
    star_four = models.IntegerField()
    star_three = models.IntegerField()
    star_two = models.IntegerField()
    star_one = models.IntegerField()
    casts = models.CharField(max_length=255, blank=True, null=True)
    directors = models.CharField(max_length=255, blank=True, null=True)
    objects = models.Manager()

    class Meta:
        managed = False
        db_table = 'info'


class PollsChoice(models.Model):
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField()
    question = models.ForeignKey('PollsQuestion', models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'polls_choice'


class PollsQuestion(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'polls_question'


class Rate(models.Model):
    id = models.BigAutoField(primary_key=True)
    user_id = models.CharField(max_length=255, blank=True, null=True)
    movie_id = models.IntegerField(blank=True, null=True)
    star = models.IntegerField(blank=True, null=True)
    objects = models.Manager()

    class Meta:
        managed = False
        db_table = 'rate'


class User(models.Model):
    id = models.CharField(primary_key=True, max_length=255)
    name = models.CharField(max_length=255, blank=True, null=True)
    genres = models.CharField(max_length=255, blank=True, null=True)
    image = models.CharField(max_length=255, blank=True, null=True)
    time = models.CharField(max_length=255, blank=True, null=True)
    password = models.CharField(max_length=255,null=False, default='123456')
    email = models.CharField(max_length=255, blank=True, null=True)
    gender = models.CharField(max_length=255, blank=True, null=True)
    objects = models.Manager()

    class Meta:
        managed = False
        db_table = 'user'

movies/views.py
from django.shortcuts import render,get_object_or_404,redirect,reverse
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.db.models import Q
import math, json
# 导入数据
from .models import Info,User,Rate
from .form import UserForm,RegisterForm

##########################################################################################

from ml.engine import get_dataset, calc_user_sim, evaluate, recommend
trainSet, testSet = get_dataset(filename = 'ml/rating.csv', pivot=1)
user_sim_matrix, movie_count = calc_user_sim(trainSet)
n_sim_user = 10
n_rec_movie = 20


##########################################################################################


# Create your views here.

# 主界面
def index(request):
    context = {'infos': Info.objects.all().order_by('-star_five')[:12],
                'topten': Info.objects.all()[:10]}
    #已经登录
    # if request.session.get('is_login',None):
    #     print('主界面推荐内容')
    #     data = []
    #     print(request.session['recommend_list'] )
    #     for i in request.session['recommend_list']:
    #         data.append(Info.objects.get(id=i))
    #     context['infos'] = data

    if request.session.get('is_login',None):
        global n_sim_user
        global n_rec_movie
        global user_sim_matrix
        global movie_count
        global trainSet
        global testSet
        rec_list = recommend(request.session['user_id'], n_sim_user, n_rec_movie, trainSet, user_sim_matrix)
        print('开始生成推荐列表')
        data = []
        for i in rec_list:
            data.append(Info.objects.get(id=i[0]))
        context['infos'] = data
    return render(request, 'movies/base.html',context)    

# 电影信息详情
def detail(request,movie_id):
    info = get_object_or_404(Info, pk=movie_id)
    genres = info.genres.split(',')
    rating_sum = info.star_five + info.star_four + info.star_three + info.star_two + info.star_one
    if rating_sum != 0:
        aver = round((info.star_five*10 + info.star_four*8 + info.star_three*6 + info.star_two*4 + info.star_one*2)/rating_sum,1)
    else:
        aver = 0
    bigstar = math.ceil(aver)*5
    five=0
    four=0
    three=0
    two=0
    one = 0
    if rating_sum != 0:
        five = info.star_five*100//rating_sum
        four = info.star_four*100//rating_sum
        three = info.star_three*100//rating_sum
        two = info.star_two*100//rating_sum
        one = info.star_one*100//rating_sum
    # 查询是否已经评价过
    if request.session.get('is_login', None):
        rate = Rate.objects.filter(movie_id=movie_id, user_id=request.session['user_id'])
        if rate:
            return render(request, 'movies/detail2.html', {'info': info,'genres':genres,'aver':aver,'bigstar':bigstar,'rating_sum':rating_sum,
                    'five':five,'four':four,'three':three,'two':two,'one':one,'star':rate[0].star})
    return render(request, 'movies/detail2.html', {'info': info,'genres':genres,'aver':aver,'bigstar':bigstar,'rating_sum':rating_sum,
                    'five':five,'four':four,'three':three,'two':two,'one':one})

def search(request):
    keyword = request.POST.get('keyword')
    if(request.method == 'POST'):
        infos = Info.objects.filter(Q(title__icontains=keyword)\
		|Q(genres__icontains=keyword)|Q(countries__icontains=keyword))
        context = {'infos':infos}
        print('搜索内容:')
        print(context)
        return render(request, 'movies/search.html',context)

def user(request, user_id):
    rates = Rate.objects.filter(user_id=user_id).order_by('-id')
    data = []
    for rate in rates:
        dic = {}
        dic['star'] = rate.star
        dic['info'] = Info.objects.get(id=rate.movie_id)
        print('评价列表')
        print(dic)
        data.append(dic)
    return render(request, 'movies/user.html', {'data':data})


def rate(request,movie_id):
    if(request.method == 'POST'):
        print("the POST method")
        postBody = request.body
        star = json.loads(postBody)['star']
        user_id = request.session['user_id']
        print('user_id:{}为电影movie_id:{}评价了{}星级'.format(user_id, movie_id, star))
        # 回调给前端的data
        data = {}
        try:
            rate = Rate.objects.get(user_id=user_id,movie_id=movie_id)
            data['code'] = 0
            data['msg'] = '已经评价过了'
        except :
            try:
                new_rate = Rate.objects.create()
                new_rate.user_id = user_id
                new_rate.movie_id = movie_id
                new_rate.star = star
                new_rate.save()
                data['code'] = 1
                data['msg'] = '评价成功'
            except:
                data['code'] = 0
                data['msg'] = '评价失败'
        
        return HttpResponse(json.dumps(data))

def login(request):

    if request.session.get('is_login',None):
        return redirect('/movies/')

    if request.method == "POST":
        login_form = UserForm(request.POST)
        message = "请检查填写的内容！"
        if login_form.is_valid():
            username = login_form.cleaned_data['username']
            password = login_form.cleaned_data['password']
            try:
                user = User.objects.get(id=username)
                if user.password == password:
                    request.session['is_login'] = True
                    request.session['user_id'] = user.id
                    request.session['user_name'] = user.name

                    # 生成个性化推荐列表

                    # global n_sim_user
                    # global n_rec_movie
                    # global user_sim_matrix
                    # global movie_count
                    # global trainSet
                    # global testSet
                    # rec_list = recommend(user, n_sim_user, n_rec_movie, trainSet, user_sim_matrix)
                    # print('开始生成推荐列表')
                    # print(rec_list)
                    # request.session['recommend_list'] = rec_list

                    return redirect('/movies/')
                else:
                    message = "密码不正确！"
            except:
                message = "用户不存在！"
        return render(request, 'movies/login.html', locals())

    login_form = UserForm()
    return render(request, 'movies/login.html', locals())




def logout(request):
    if not request.session.get('is_login', None):
        # 如果本来就未登录，也就没有登出一说
        return redirect("/movies/")
    request.session.flush()
    recommend_list=[]
    # 或者使用下面的方法
    # del request.session['is_login']
    # del request.session['user_id']
    # del request.session['user_name']
    return redirect("/movies/")


def rec(request):
    global n_sim_user
    global n_rec_movie
    global user_sim_matrix
    global movie_count
    global trainSet
    global testSet
    rec_list = recommend('beijinglife', n_sim_user, n_rec_movie, trainSet, user_sim_matrix)
    print('开始生成推荐列表')
    rec_list = [i[0] for i in rec_list]
    return HttpResponse(rec_list)

def register(request):
    if request.session.get('is_login', None):
        # 登录状态不允许注册。你可以修改这条原则！
        return redirect("/movies/")
    if request.method == "POST":
        register_form = RegisterForm(request.POST)
        message = "请检查填写的内容！"
        if register_form.is_valid():  # 获取数据
            username = register_form.cleaned_data['username']
            password1 = register_form.cleaned_data['password1']
            password2 = register_form.cleaned_data['password2']
            email = register_form.cleaned_data['email']
            sex = register_form.cleaned_data['sex']
            if password1 != password2:  # 判断两次密码是否相同
                message = "两次输入的密码不同！"
                return render(request, 'login/register.html', locals())
            else:
                same_name_user = User.objects.filter(id=username)
                if same_name_user:  # 用户名唯一
                    message = '用户已经存在，请重新选择用户名！'
                    return render(request, 'movies/register.html', locals())
                same_email_user = User.objects.filter(email=email)
                if same_email_user:  # 邮箱地址唯一
                    message = '该邮箱地址已被注册，请使用别的邮箱！'
                    return render(request, 'movies/register.html', locals())

                # 当一切都OK的情况下，创建新用户
                print('ok')
                new_user = User.objects.create(id=username)
                new_user.password = password1
                new_user.email = email
                new_user.gender = sex
                new_user.save()
                return redirect('/movies/login')  # 自动跳转到登录页面
    register_form = RegisterForm()
    return render(request, 'movies/register.html', locals())

movies/templates/movies/base.html
{% load static %}

<!DOCTYPE html>
<html lang="zh-CN">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="referrer" content="never">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->
    <title>{% block title %}主页{% endblock %}</title>

    <!-- Bootstrap -->
    <link href="{% static 'movies/bootstrap-3.3.7-dist/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://cdn.bootcss.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://cdn.bootcss.com/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
    {% block css %}
    <link rel="stylesheet" href="{% static 'movies/css/index.css' %}">
    {% endblock %}
  </head>
  <body>
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#my-nav" aria-expanded="false">
            <span class="sr-only">切换导航条</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Mysite</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="my-nav">
          <ul class="nav navbar-nav">
            <li class="active"><a href="{% url 'movies:index' %}">主页</a></li>
          </ul>
          {% if infos %}
          <form class="navbar-form navbar-left" action="search" method="post">
            <div class="form-group">
              <input type="text" name="keyword" class="form-control" placeholder="Search">
            </div>
            <button type="submit" class="btn btn-default">搜索</button>
          </form>
          {% endif %}
          <ul class="nav navbar-nav navbar-right">
            {% if request.session.is_login %}
                <li><a href="{% url 'movies:user' request.session.user_id %}">当前在线：{{ request.session.user_name }}</a></li>
                <li><a href="{% url 'movies:logout' %}">登出</a></li>
            {% else %}
                <li><a href="{% url 'movies:login' %}">登录</a></li>
                <li><a href="{% url 'movies:register' %}">注册</a></li>
            {% endif %}
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>

    {% block content %}
    {% if request.session.is_login %}
    {% else %}
    <div>你尚未登录，只能进行非个性化推荐！</div>
    {% endif %}

    <div class="body">
        <main>
            <div class="content">
    {% if infos %}
      {% for info in infos %}
                <div class="card">
        <a href="{% url 'movies:detail' info.id %}">
        <img src="{{ info.image }}" alt="图片" />
        </a>
                    <div class="disc">
          {{ info.title }}
        </div>
      </div>
      {% endfor %}
    {% endif %}
            </div>
            <aside>
                <ul>
          <li>近期热门影片</li>
        {% if topten %}
          {% for i in topten %}
          <li>
            <a href="{% url 'movies:detail' i.id %}">{{ forloop.counter }}.{{ i.title }}</a>
          </li>
          {% endfor %}
        {% endif %}
                </ul>
            </aside>
        </main>
    </div>
    {% endblock %}


    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="{% static 'movies/js/jquery-3.3.1.js' %}"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="{% static 'movies/bootstrap-3.3.7-dist/js/bootstrap.min.js' %}"></script>
  </body>
</html>

movies/templates/movies/index.html
<!DOCTYPE html>
<html lang="en">
	<head>
    <meta charset="UTF-8" />
    <meta name="referrer" content="never">
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
		<title>Document</title>
		<style>
			* {
        margin: 0;
        padding: 0;
      }
      li {
        list-style-type: none;
      }
      body,
      html {
        height: 100%;
      }
      body {
        display: flex;
        flex-direction: column;
      }
      header {
        height: 40px;
        background-color: green;
        display: flex;
        justify-content: center;
      }
      header > .content {
        display: flex;
        justify-content: space-between;
        width: 800px;
        margin: 0 auto;
      }
      div.body {
        display: flex;
        flex: 1;
        justify-content:center;
      }
      main {
        display: flex;
        width: 800px;
      }
      main > .content {
        display: flex;
        flex: 1;
        height: 100%;
        background-color: blue;
      }
      main > aside {
        width: 200px;
        background-color: orange;
        padding: 20px;
      }
      main > .content {
        display: flex;
        flex-wrap: wrap;
      }

      .content > .card {
        width: 100px;
        height: 150px;
        padding: 10px;
      }

      .card > a > img {
        display: block;
        width: 100px;
        height: 100px;
        background-color: red;
      }
      .card > .disc {
        color: #fff;
        text-align: center;
      }
    </style>
	</head>
	<body>
		<header>
			<div class="content">
				<div class="search">
					<input type="text" placeholder="Search" />
				</div>
				<nav class="menu">
					<button>注册</button>
					<button>登录</button>
				</nav>
			</div>
		</header>
		<div class="body">
			<main>
				<div class="content">
        {% if infos %}
          {% for info in infos %}
					<div class="card">
            <a href="{% url 'movies:detail' info.id %}">
            <img src="{{ info.image }}" alt="图片" />
            </a>
						<div class="disc">
              {{ info.title }}
            </div>
          </div>
          {% endfor %}
        {% endif %}
				</div>
				<aside>
					<ul>
              <li>近期热门影片</li>
            {% if topten %}
              {% for i in topten %}
              <li>
                <a href="{% url 'movies:detail' i.id %}">{{ forloop.counter }}.{{ i.title }}</a>
              </li>
              {% endfor %}
            {% endif %}
					</ul>
				</aside>
			</main>
		</div>

	</body>
</html>

movies/templates/movies/login.html
{% extends 'movies/base.html' %}
{% load static %}
{% block title %}登录{% endblock %}
{% block css %}
    <link rel="stylesheet" href="{% static 'movies/css/login.css' %}">
{% endblock %}


{% block content %}
<div class="container">
    <div class="col-md-4 col-md-offset-4">
      <form class='form-login' action="" method="post">

          {% if message %}
              <div class="alert alert-warning">{{ message }}</div>
          {% endif %}
          {% csrf_token %}
          <h2 class="text-center">欢迎登录</h2>

          {{ login_form }}

          <button type="reset" class="btn btn-default pull-left">重置</button>
          <button type="submit" class="btn btn-primary pull-right">提交</button>

      </form>
    </div>
</div> <!-- /container -->
{% endblock %}

movies/templates/movies/register.html
{% extends 'movies/base.html' %}

{% block title %}注册{% endblock %}
{% block content %}
    <div class="container">
        <div class="col-md-4 col-md-offset-4">
          <form class='form-register' action="" method="post">

              {% if message %}
                  <div class="alert alert-warning">{{ message }}</div>
              {% endif %}

              {% csrf_token %}

              <h2 class="text-center">欢迎注册</h2>
              <div class="form-group">
                  {{ register_form.username.label_tag }}
                  {{ register_form.username}}
              </div>
              <div class="form-group">
                  {{ register_form.password1.label_tag }}
                  {{ register_form.password1 }}
              </div>
              <div class="form-group">
                  {{ register_form.password2.label_tag }}
                  {{ register_form.password2 }}
              </div>
              <div class="form-group">
                  {{ register_form.email.label_tag }}
                  {{ register_form.email }}
              </div>
              <div class="form-group">
                  {{ register_form.sex.label_tag }}
                  {{ register_form.sex }}
              </div>
              <div class="form-group">
                  {{ register_form.captcha.errors }}
                  {{ register_form.captcha.label_tag }}
                  {{ register_form.captcha }}
              </div>

              <button type="reset" class="btn btn-default pull-left">重置</button>
              <button type="submit" class="btn btn-primary pull-right">提交</button>

          </form>
        </div>
    </div> <!-- /container -->
{% endblock %}

movies/templates/movies/search.html
{% extends 'movies/base.html' %}
{% load static %}
{% load my_tag %}
{% block title %}搜索{% endblock %}
{% block css %}
    <link rel="stylesheet" href="{% static 'movies/css/login.css' %}">
    <link rel="apple-touch-icon"
		href="https://img3.doubanio.com/f/movie/d59b2715fdea4968a450ee5f6c95c7d7a2030065/pics/movie/apple-touch-icon.png">
	<link href="https://img3.doubanio.com/f/shire/52c9997d6d42db58eab418e976a14d5f3eff981e/css/douban.css"
		rel="stylesheet" type="text/css">
	<link href="https://img3.doubanio.com/f/shire/ae3f5a3e3085968370b1fc63afcecb22d3284848/css/separation/_all.css"
		rel="stylesheet" type="text/css">
	<link href="https://img3.doubanio.com/f/movie/8864d3756094f5272d3c93e30ee2e324665855b0/css/movie/base/init.css"
		rel="stylesheet">
	<script type="text/javascript">
		var _head_start = new Date();
	</script>
	<script type="text/javascript"
		src="https://img3.doubanio.com/f/movie/0495cb173e298c28593766009c7b0a953246c5b5/js/movie/lib/jquery.js">
	</script>
	<script type="text/javascript"
		src="https://img3.doubanio.com/f/shire/1316664523258f7b8b536e4ce45afc9cb37b8963/js/douban.js"></script>
	<script type="text/javascript"
		src="https://img3.doubanio.com/f/shire/0efdc63b77f895eaf85281fb0e44d435c6239a3f/js/separation/_all.js"></script>
	<link href="https://img3.doubanio.com/f/movie/2c95f768ea74284b900c04c0209b0a44f0a0de52/css/movie/top_movies.css"
		rel="stylesheet" type="text/css" />
	<script type="text/javascript"
		src="https://img3.doubanio.com/f/shire/77323ae72a612bba8b65f845491513ff3329b1bb/js/do.js"
		data-cfg-autoload="false"></script>
	<script type='text/javascript'>
		Do.ready(function () {
			$("#mine-selector input[type='checkbox']").click(function () {
				var val = $(this).is(":checked") ? $(this).val() : "";
				window.location.href = '/top250?filter=' + val;
			})
		})
	</script>
	<style type="text/css">
		.site-nav-logo img {
			margin-bottom: 0;
		}
	</style>
	<style type="text/css">
		img {
			max-width: 100%;
		}
	</style>
	<script type="text/javascript"></script>
	<link rel="stylesheet" href="https://img3.doubanio.com/misc/mixed_static/562925b5e3824700.css">
	<link rel="shortcut icon" href="https://img3.doubanio.com/favicon.ico" type="image/x-icon">
{% endblock %}


{% block content %}
<div id="wrapper">
    <div id="content">
        <h1>搜索结果</h1>
        <div class="grid-16-8 clearfix">
            <div class="article">


                <ol class="grid_view">


                    {% for movie in infos %}
                    <li>
                        <div class="item">
                            <div class="pic">
                                <em class="">{{ forloop.counter }}</em>
                                <a href="{% url 'movies:detail' movie.id %}">
                                    <img width="100" alt="图片" src= "{{ movie.image }}" class="">
                                </a>
                            </div>
                            <div class="info">
                                <div class="hd">
                                    <a href="{% url 'movies:detail' movie.id %}" class="">
                                        <span class="title">{{movie.title}}</span>
                                    </a>
                                </div>
                                <div class="bd">
                                    <p class="">
                                        时长&nbsp;&nbsp;&nbsp;{{movie.durations}}<br>
                                        上映时间&nbsp;&nbsp;{{movie.pubdates}}<br>
                                        种类&nbsp;&nbsp;{{movie.genres}}
                                    </p>
                                    <div class="star">
                                        <span class= "{% starround movie.star_five movie.star_four movie.star_three movie.star_two movie.star_one %}" ></span>
                                        <span class="rating_num" property="v:average">{% startag movie.star_five movie.star_four movie.star_three movie.star_two movie.star_one %}</span>
                                        <span property="v:best" content="10.0"></span>
                                    </div>

                                </div>
                            </div>
                        </div>
                    </li>
                    {% endfor %}


                </ol>
                
            </div>

            <div class="extra">
            </div>
        </div>
    </div>
    <div id="footer">
        <div class="footer-extra"></div>
    </div>
</div>
{% endblock %}